version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  ezyshop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ezyshop
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/
      
volumes:
  mongodb_data:
